// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationType string

const (
	NotificationTypeInfo    NotificationType = "info"
	NotificationTypeWarning NotificationType = "warning"
	NotificationTypeAlert   NotificationType = "alert"
	NotificationTypeSuccess NotificationType = "success"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notificationType"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type TransactionType string

const (
	TransactionTypeIncome  TransactionType = "income"
	TransactionTypeExpense TransactionType = "expense"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transactionType"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type BudgetTemplate struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"userId"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	GlobalBudget pgtype.Numeric     `json:"globalBudget"`
	Categories   []byte             `json:"categories"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"userId"`
	Name        string             `json:"name"`
	Color       string             `json:"color"`
	Type        TransactionType    `json:"type"`
	BudgetLimit pgtype.Numeric     `json:"budgetLimit"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"userId"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	Type      NotificationType   `json:"type"`
	Date      pgtype.Timestamptz `json:"date"`
	IsRead    bool               `json:"isRead"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Transaction struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"userId"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description pgtype.Text        `json:"description"`
	CategoryID  pgtype.UUID        `json:"categoryId"`
	Date        pgtype.Timestamptz `json:"date"`
	Type        TransactionType    `json:"type"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"passwordHash"`
	Currency           string             `json:"currency"`
	CurrencySymbol     string             `json:"currencySymbol"`
	MonthlyIncome      pgtype.Numeric     `json:"monthlyIncome"`
	OnboardingComplete bool               `json:"onboardingComplete"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}
